config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  get 'organizations/index'
  get 'organizations/admin_index'
  get 'organizations/:id/super_fetaure_edit', to: 'organizations#super_fetaure_edit', as: :super_fetaure_edit
  patch 'organizations/:id', to: 'organizations#super_fetaure_update', as: :super_fetaure_update
  get 'properties/index'
  get 'users/index'
  get 'periods/index'
  get 'periods/new'
  get 'passwords/edit', to: 'passwords#edit'
  post 'updates/new'
  post 'leave_applications/new'
  post 'leave_applications/get_calculated_leaves'
  get  'employees',  to: 'users#new'
  post 'employees',  to: 'users#add_user'
  get 'leave_balances/index'
  get 'users/switch_and_redirect_view'
  resources :passwords do
    member do
      get 'edit_password'
      patch 'edit_password'
      patch 'update_password'
    end
  end
  resources :leave_days 
  resources :notifications 
  resources :organizations
  resources :properties
  resources :bonds

  resources :groups do 
    resources :messages
  end

  resources :users do
    member do
      get 'user_profile'
      get 'edit_user'
      patch 'edit_user'
      patch 'update_user'
      post 'assign_admin_role'
      post 'remove_admin_role'
      resources :projects
    end
  end
  
  resources :updates do 
    collection { post :import}
  end
  
  resources :leave_applications do
    member do
      patch 'approve'
      get 'approve'
      patch 'reject'
      get 'reject'
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :projects
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_admin_navbar.html.erb
<li class="nav-item">
  <%= link_to 'Home', root_path, class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Organization', organizations_admin_index_path , class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'User', users_index_path, class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Holiday', leave_days_path , class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Daily Update', updates_path, class: "nav-link active mr-auto", target: "_top" %>
</li>
<li class="nav-item">
  <%= link_to 'Asset', properties_index_path, class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Project', projects_path(current_user.id) , class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Chat', groups_path, class: "nav-link active mr-auto" %>
</li>
<% if current_user.organization.feature_flag.present? && current_user.organization.feature_flag.employee_bond == 'on' %>
  <li class="nav-item">
    <%= link_to 'Bond', bonds_path ,class: "nav-link active mr-auto" %>
  <li>
<% end %>
<li class="nav-item">
  <%= link_to pending_leave > 0 ? "Leave <span class='badge badge-light'>#{pending_leave}</span>".html_safe : "Leaves",
  leave_applications_path , target: "_top",
  class: pending_leave > 0 ? "btn btn-outline-light btn-sm mt-1" : "nav-link active" %>
</li>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <% if user_signed_in? %>
    <div class="container-fluid">   
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <% if current_user.has_role? :superadmin%>
          <%= render 'shared/super_admin_navbar'%>
        <% elsif current_user.has_role? :admin %>
          <% if cookies[:is_user_view].present? %>
            <%= render 'shared/user_navbar'%>
          <% else %>
            <%= render 'shared/admin_navbar'%>
          <% end %>
        <% elsif current_user.has_role? :newuser || cookies[:is_user_view].present?%>
          <%= render 'shared/user_navbar'%>
        <% end %>
      </ul>
      <div class="dropdown-right">
        <ul class="navbar-nav ml-auto mr-4">
          <li class="nav-item dropdown-right">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><span class="dropdown-item"><%= current_user.email%></span></li>
              <li><div class="dropdown-divider"></div></li>
              <%= link_to "Your Profile", user_profile_user_path(current_user.id), class: "dropdown-item text-primary"%>
              <%= link_to "Change Password", edit_password_path(current_user.id), class: "dropdown-item text-primary"%>
              <li><div class="dropdown-divider"></div></li>
              <% if current_user.has_all_roles? :admin, :newuser %>
                <%= link_to "Switch Role", users_switch_and_redirect_view_path, class: "dropdown-item text-primary"%>
                <li><div class="dropdown-divider"></div></li>
              <% end %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item text-primary"%>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="container-fluid">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <div class="collapse navbar-collapse" id=""> 
          <span class="mr-auto" style="color:white">Employee Portal</span>
        </div>
      </ul>
      <div class="dropdown-right">
        <ul class="navbar-nav ml-auto mr-4">
          <li class="nav-item dropdown-right">
            <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
</nav>

app/views/shared/_super_admin_navbar.html.erb
<li class="nav-item">
  <%= link_to 'Organization', organizations_index_path , class: "nav-link active mr-auto" %>
</li>

app/views/shared/_user_navbar.html.erb
<li class="nav-item">
  <%= link_to 'Home', root_path, class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Daily Update', updates_path, class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Asset', properties_index_path, class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Project', projects_path(current_user.id) , class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Holiday', leave_days_path , class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Chat', groups_path, class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Leave', leave_applications_path, target: "_top", class: "nav-link active mr-auto" %>
</li>
<li class="nav-item">
  <%= link_to 'Leave Balance', leave_balances_index_path, target: "_top", class: "nav-link active mr-auto" %>
</li>