config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  get 'organizations/index'
  get 'organizations/admin_index'
  get 'organizations/:id/super_fetaure_edit', to: 'organizations#super_fetaure_edit', as: :super_fetaure_edit
  patch 'organizations/:id', to: 'organizations#super_fetaure_update', as: :super_fetaure_update
  get 'properties/index'
  get 'users/index'
  get 'periods/index'
  get 'periods/new'
  get 'passwords/edit', to: 'passwords#edit'
  post 'updates/new'
  post 'leave_applications/new'
  post 'leave_applications/get_calculated_leaves'
  get  'employees',  to: 'users#new'
  post 'employees',  to: 'users#add_user'
  get 'leave_balances/index'
  get 'users/switch_and_redirect_view'
  resources :passwords do
    member do
      get 'edit_password'
      patch 'edit_password'
      patch 'update_password'
    end
  end
  resources :leave_days 
  resources :notifications 
  resources :organizations
  resources :properties
  resources :bonds

  resources :groups do 
    resources :messages
  end

  resources :users do
    member do
      get 'user_profile'
      get 'edit_user'
      patch 'edit_user'
      patch 'update_user'
      post 'assign_admin_role'
      post 'remove_admin_role'
      resources :projects
    end
  end
  
  resources :updates do 
    collection { post :import}
  end
  
  resources :leave_applications do
    member do
      patch 'approve'
      get 'approve'
      patch 'reject'
      get 'reject'
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :projects
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :periods, dependent: :destroy
  has_many :users, through: :periods
  has_many :updates, dependent: :destroy
  belongs_to :organization

  validates :name, presence: true

  def self.count_hour(project, user, start_date, end_date)
    if start_date.present? && end_date.present?
      @total_hours = Update.where("project_id = ? AND user_id = ? AND DATE(created_at) BETWEEN ? AND ?", project, user, start_date.to_date.strftime('%Y-%m-%d'), end_date.to_date.strftime('%Y-%m-%d')).sum(:total_hours)
    else
      @total_hours = Update.where("project_id = ? AND user_id = ? AND created_at BETWEEN ? AND ?", project, user, Date.today.beginning_of_month, Date.today.end_of_month).sum(:total_hours)
    end
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < ApplicationController
  def index
    @users = User.where('organization_id = ? AND name ILIKE?',current_user.organization_id,  "%#{params[:name]}%")
    render json: {data: @users}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_user
  before_action :set_project, only: %i[edit update destroy]
  before_action :get_users, only: [:new, :create, :edit, :update]

  def index
    @projects = if has_role_admin?
                  Project.where(organization_id: current_user.organization_id)
                else
                  current_user.projects
                end
    @projects = @projects.page(params[:page]).per(5)
    @periods = Period.all
  end

  def show
    @project = Project.find(params[:id])
    @users = @project.users
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params.merge(organization_id: current_user.organization_id))
    if @project.save
      redirect_to projects_url, notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity 
    end 
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_url, notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def find_user
    @user = current_user
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :organization_id, user_ids: [])
  end

  def get_users
    @users_array = User.where(organization_id: current_user.organization_id).order(name: :asc).map { |c| [c.name, c.id] }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="row">
  <div class="field col-12">
    <% invalid = @project.errors.include?(:name) %>
    <div class="form-group">
      <%= form.text_field :name, class: "form-control #{'is-invalid' if invalid}", placeholder: "Name" %>
      <% if invalid %>
        <div class="invalid-feedback d-block">
          <% @project.errors.full_messages_for(:name).each do |error_message| %>
            <%= error_message %>.
          <% end %>
        </div>
      <% end %>
    </div><br>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form.select :user_ids, options_for_select(@users_array, selected: params[:user_id]),{ include_blank: false}, id:"choices-multiple-remove-button", class: "form-control", multiple: true, placeholder: "select user" %>
  </div>
</div><br>  

            

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <%= project.name %>
  </p>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card my-5 shadow">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h3>Edit Project</h3><br>
            </div>
            <div class="col-md-7 text-end">
              <%= link_to projects_path, class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Back' do %>
                <i class='bi bi-arrow-left' aria-hidden='true'></i>
              <% end %>
            </div>
            <%= form_for @project, :url => {:controller => 'projects',:action => 'update'}, data: {turbo: false} do |form| %>
              <%= render 'form', :form => form %>
              <div class="col-md-12 text-end"><br />
                <%= form.submit "Update", class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Update' %>
              </div>
            <% end %>
          </div>
         </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
      <div class="card my-5 shadow">
        <div class="card-body">
          <div class="row">
              <div class="col">
                <h2>Project</h2><br>
              </div>
              <% if has_role_admin? %>
                <div class="col-md-7 text-end">
                <%= link_to new_project_path(@user), class: "btn btn-primary", title: 'New Project', target: "_top" do%> 
                  <i class='bi bi-plus-circle-fill' aria-hidden='true'></i> 
                <% end %>
              <% end %>
            </div>
            <table class="table">
              <thead class="thead-light">
                <tr>
                  <th>Name</th>
                  <% if has_role_admin?%>
                    <th>Action</th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <% @projects.each do |project| %>
                  <tr>
                  <% if has_role_admin? %>
                      <td><%= link_to project.name, project_path(project.id) %></td>
                      <td class="col-3">
                        <%= link_to edit_project_path(project.id), class: "btn btn-success btn-sm", data: {toggle: 'tooltip', placement: 'top'}, title: 'Edit Project' do %>
                          <i class='bi bi-pencil-fill' aria-hidden='true'></i>
                        <% end %>
                        <%= link_to project_path(project.id), method: :delete , data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm", toggle: 'tooltip', placement: 'top', title: 'Destroy Project' do %>
                          <i class='bi bi-trash3-fill' aria-hidden='true'></i>
                        <% end %>
                      </td>
                      <% else %>
                      <td><%= project.name %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="pagination justify-content-center">
              <%= paginate @projects, theme: 'bootstrap-5', pagination_class: "pagination-sm", nav_class: "d-inline-b" %>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card my-5 shadow">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h3>New Project</h3><br>
            </div>
            <div class="col-md-7 text-end">
              <%= link_to projects_path, class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Back' do %>
                <i class='bi bi-arrow-left' aria-hidden='true'></i>
              <% end %>
            </div>
            <%= form_for @project, url: projects_path, data: {turbo: false}, method: :post do |form| %>
              <%= render 'form', :form => form %></br >
              <div class="col-md-12 text-end">
                <%= form.submit "Save", class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Save' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
      <div class="card my-5 shadow">
        <div class="card-body">
          <div class="col-md-12 text-end">
            <%= link_to projects_path, class: "btn btn-primary", data: {toggle: 'tooltip', placement: 'top'}, title: 'Back' do %>
              <i class='bi bi-arrow-left' aria-hidden='true' aria-hidden='true'></i>
            <% end %>
          </div>
          <%= form_tag project_path(@project.id), data: {toggle: 'tooltip', placement: 'top' }, method: :get do %>
            <div class="row mt-4">
              <div class ="col-2">
                <div class="input-group date col-3" data-provide="date" >
                  <%= text_field_tag :from_date, params[:from_date], class: "form-control datepicker-input" %>
                  <div class="input-group-append">
                    <div class="input-group-text"><i class="bi bi-calendar3"></i></i></div>
                  </div>
                </div>
              </div>
              <div class ="col-2">
                <div class="input-group date col-3" data-provide="date" >
                  <%= text_field_tag :to_date, params[:to_date], class: "form-control datepicker-input" %>
                  <div class="input-group-append">
                    <div class="input-group-text"><i class="bi bi-calendar3"></i></i></div>
                  </div>
                </div>
              </div><br>
              <div class="col-1">
                <%= button_tag class: "btn btn-primary", data: {toggle: 'tooltip', placement: 'top'}, title: 'Find' do %>
                  <i class='bi bi-search' aria-hidden='true'></i>
                <% end %>
              </div>
              <div class="reset">
                <%= link_to project_path(@project.id), class: 'btn btn-secondary', target: "_top", title: 'Clean' do %>
                  <i class='bi bi-x-lg' aria-hidden='true'></i>
                <% end %>
              </div>
            </div><br>
          <% end %>
          <h1><%= @project.name %></h1>
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th>Employee-Name</th>
                <th>Spended Hours</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td class="col-9">
                    <%= user.name %>
                  </td>
                  <td class="col-3">
                    <%= Project.count_hour(@project.id, user.id, params[:from_date], params[:to_date]) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>