config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  get 'organizations/index'
  get 'organizations/admin_index'
  get 'organizations/:id/super_fetaure_edit', to: 'organizations#super_fetaure_edit', as: :super_fetaure_edit
  patch 'organizations/:id', to: 'organizations#super_fetaure_update', as: :super_fetaure_update
  get 'properties/index'
  get 'users/index'
  get 'periods/index'
  get 'periods/new'
  get 'passwords/edit', to: 'passwords#edit'
  post 'updates/new'
  post 'leave_applications/new'
  post 'leave_applications/get_calculated_leaves'
  get  'employees',  to: 'users#new'
  post 'employees',  to: 'users#add_user'
  get 'leave_balances/index'
  get 'users/switch_and_redirect_view'
  resources :passwords do
    member do
      get 'edit_password'
      patch 'edit_password'
      patch 'update_password'
    end
  end
  resources :leave_days 
  resources :notifications 
  resources :organizations
  resources :properties
  resources :bonds

  resources :groups do 
    resources :messages
  end

  resources :users do
    member do
      get 'user_profile'
      get 'edit_user'
      patch 'edit_user'
      patch 'update_user'
      post 'assign_admin_role'
      post 'remove_admin_role'
      resources :projects
    end
  end
  
  resources :updates do 
    collection { post :import}
  end
  
  resources :leave_applications do
    member do
      patch 'approve'
      get 'approve'
      patch 'reject'
      get 'reject'
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :projects
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/leave_application.rb
class LeaveApplication < ApplicationRecord
  belongs_to :user
  belongs_to :organization
  has_rich_text :description
  has_many :leave_balances, dependent: :destroy
  enum leave_type: { Other: 0, Personal: 1, Medical: 2, Family_Emergency: 3, Govt_Work: 4, Religious: 5, Bad_Weather: 6, Maternity: 7, Occasional:8 }
  enum :status, [:pending, :approved, :rejected], default: :pending
  validates :description, :to_date, :from_date, :leave_type, presence: true
  validate :date_scope, on: [:create, :update]
  before_create :set_default_status 
  after_update :add_leave_balance

  def total_day
    to_date > from_date ? n = ((to_date - from_date) / 1.day + 1).round : n = 1
    total = []
    total1 = []
    a = self.from_date
    while a <= self.to_date
      if self.organization.weekly_off.present?
        if self.organization.weekly_off.include?(a.strftime("%A"))
          total = total
        else
          total << a
        end
      else
        total << a
      end
      a += 1.day
    end
    self.organization.leave_days.each do |a|
      total1 << a.holiday
    end
    (total - total1).count
  end

  private
  def date_scope
    if to_date.present? && from_date.present? && (to_date < from_date)
      errors.add(:from_date, 'must be past to to_date or equal')
    end

    if half_day?
      errors.add(:to_time, "can't be blank") unless to_time.present?
      errors.add(:from_time, "can't be blank") unless from_time.present?
      
      if to_date.present? && from_date.present? && (to_date != from_date)
        errors.add(:to_date, '& from date must be same')
      end

    else
      errors.add(:to_time, 'must be blank if half_day not checked') if to_time.present?
      errors.add(:from_time, 'must be blank if half_day not checked') if from_time.present?
    end
  end

  def set_default_status
    self.status ||= :pending
  end

  def add_leave_balance
    if self.status == "approved"
      leave_dates = self.from_date
      while leave_dates <= self.to_date
        b = LeaveBalance.new
        b.leave_application_id = self.id
        b.user_id = self.user_id
        b.organization_id = self.organization_id
        b.leave_date = leave_dates
        b.save!
        leave_dates += 1.day
      end
    end
  end

  def self.display_month_leaves(beginning_month, end_month, user, organization)
    monthly_leaves = LeaveApplication.where("user_id = ? AND organization_id = ? AND status = ? AND ((DATE(from_date) BETWEEN ? AND ?) OR (DATE(to_date) BETWEEN ? AND ?))", user, organization, 1, beginning_month, end_month, beginning_month, end_month)
  end
end 

app/controllers/leave_applications_controller.rb
class LeaveApplicationsController < ApplicationController
  before_action :find_user
  before_action :get_users, only: %i[index]

  def index
    @leave_applications = if current_user.has_role_admin
                            LeaveApplication.joins(:user).where(
                              users: { organization_id: current_user.organization_id }
                            ).order('leave_applications.from_date DESC')
                          else
                            LeaveApplication.where(user_id: current_user).order('from_date DESC')
                          end

    @leaves = if params[:user_id].present? && params[:status].present?
                @leave_applications.where(user_id: params[:user_id], status: params[:status])
              elsif params[:user_id].present?
                @leave_applications.where(user_id: params[:user_id])
              elsif params[:status].present?
                @leave_applications.where(status: params[:status])
              elsif params[:order].present?
                params[:order] == "ASC" ? @leave_applications.all.reorder('from_date ASC') : @leave_applications
              elsif params[:from_date].present? && params[:to_date].present?
                @leave_applications.where("((DATE(from_date) BETWEEN ? AND ?) AND (DATE(to_date) BETWEEN ? AND ?)) OR ((? BETWEEN DATE(from_date) AND DATE(to_date)) OR (? BETWEEN DATE(from_date) AND DATE(to_date)))", set_format(params[:from_date]), set_format(params[:to_date]), set_format(params[:from_date]), set_format(params[:to_date]), set_format(params[:from_date]), set_format(params[:to_date]))
              elsif params[:from_date].present?
                @leave_applications.where("? BETWEEN from_date AND to_date ", set_format(params[:from_date]))
              else 
                @leave_applications.all
              end
              
    @leaves = @leaves.page(params[:page]).per(5)
  end

  def new
    @leave_application = LeaveApplication.new
  end

  def create
    @leave_application = LeaveApplication.new(
      leave_params.merge(organization_id: current_user.organization_id, user_id: current_user.id)
    )
    respond_to do |format|
      if @leave_application.save
        format.html { redirect_to leave_applications_path, notice: 'Leave Application Created Sucessfully' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('leave_application_form',
          partial: 'leave_applications/form',
          locals: { leave_application: @leave_application })
        end
        format.html { render :new, status: :unprocessable_entity}
      end
    end
  end

  def edit
    @leave_application = LeaveApplication.find(params[:id])
  end

  def update
    @leave_application = LeaveApplication.find(params[:id])
    if current_user.id == @leave_application.user_id
      respond_to do |format|
        if @leave_application.update(leave_params)
          format.html { redirect_to leave_applications_path, notice: 'Your LeaveApplication Was Successfully Updated.' }
          format.json { render :show, status: :ok, location: @leave_application }
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('leave_application_form', partial: 'leave_applications/form',
              locals: { leave_application: @leave_application })
          end
          format.html { render :edit, status: :unprocessable_entity}
        end
      end
    else
      redirect_to leave_applications_path
    end
  end

  def approve
    @leave_application = LeaveApplication.find(params[:id])
    @leave_application.status = 'approved'
    @leave_application.apporved_by = current_user.name
    if @leave_application.update(status: 'approved', apporved_by: current_user.name)
      if URI(request.referer).path == '/leave_applications'
        redirect_to leave_applications_path, notice: 'Leaves Approve Succsesfully'
      else
        redirect_to root_path, notice: 'Leaves Approve Succsesfully'
      end
    else
      redirect_to leave_applications_path, notice: 'Something went wrong'
    end
  end

  def reject
    @leave_application = LeaveApplication.find(params[:id])
    @leave_application.status = 'rejected'
    @leave_application.apporved_by = current_user.name
    if @leave_application.update(status: 'rejected', apporved_by: current_user.name)
      if URI(request.referer).path == '/leave_applications'
        redirect_to leave_applications_path, notice: 'Leaves Reject Succsesfully'
      else
        redirect_to root_path, notice: 'Leaves Reject Succsesfully'
      end
    else
      redirect_to leave_applications_path, notice: 'Something went wrong'
    end
  end

  def get_calculated_leaves
    Organization.calculated_lefted_leaves_of_the_month(current_user.organization)
    redirect_to leave_applications_path
  end

  private

  def leave_params
    params.require(:leave_application).permit(:description, :from_time, :to_date, :from_date, :to_time, :half_day, :leave_type, :organization_id, :user_id)
  end

  def find_user
    @user = current_user
  end

  def set_format(date)
    dates = date.to_date
    dates.strftime('%Y-%m-%d')
  end

  def get_users
    @users_array = User.where(organization_id: current_user.organization_id).order(name: :asc).map { |c| [c.name, c.id] }
    @status = LeaveApplication.statuses.keys.collect { |s| [s.upcase, s] }
    @order = [ "ASC", "DESC" ]
  end
end

app/helpers/leave_applications_helper.rb
module LeaveApplicationsHelper
  def pending_leave
    @leave_applications = LeaveApplication.joins(:user).where(
        users: { organization_id: current_user.organization_id }
      )
    @leave_applications = @leave_applications.where(status: "pending").count 
  end
end

app/views/leave_applications/_form.html.erb
<div class="row">
  <div class="field col-5">
    <% invalid = @leave_application.errors.include?(:from_date) %>
      <div class="form-group">
        <%= form.label :From_Date%>
        <div class="input-group date">
          <%= form.text_field :from_date, class: "form-control datepicker-input #{'is-invalid' if invalid}", value: @leave_application.from_date&.strftime("%d-%m-%Y") %>
          <div class="input-group-append">
            <div class="input-group-text"><i class="bi bi-calendar3"></i></i></div>
          </div>
          <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @leave_application.errors.full_messages_for(:from_date).each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
  <div class="field col-5">
    <% invalid = @leave_application.errors.include?(:to_date) %>
      <div class="form-group">
        <%= form.label :To_Date%>
        <div class="input-group date" data-provide="date">
          <%= form.text_field :to_date, class: "form-control datepicker-input #{'is-invalid' if invalid}", value: @leave_application.to_date&.strftime("%d-%m-%Y") %>
          <div class="input-group-append">
            <div class="input-group-text"><i class="bi bi-calendar3"></i></i></div>
          </div>
          <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @leave_application.errors.full_messages_for(:to_date).each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
  </div>
  <div class="field col-2">
    <% invalid = @leave_application.errors.include?(:leave_type) %>
      <div class="from-group">
        <%= form.label :Leave_type%>
        <%= form.select :leave_type, options_for_select(LeaveApplication.leave_types.keys ,selected: form.object.leave_type ) ,{ include_blank: "Select Leave Type"}, {class: "form-control #{'is-invalid' if invalid}"} %>
        <% if invalid %>
          <div class="invalid-feedback d-block">
            <% @leave_application.errors.full_messages_for(:leave_type).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </div>
        <% end %>
      </div>
  </div>
  <div class="field">
    <%= form.label :half_day %>
    <%= form.check_box :half_day, id: "checkbox" %>
  </div>
  <div id="half_day_div" class="<%= @leave_application.half_day ? 'd-block' : 'd-none' %>">
    <div class="row">
      <div class="col">
        <% invalid = @leave_application.errors.include?(:from_time) %>
        <div class="from-group">
          <%= form.label :from_time %>
          <div class="input-group date" data-target-input="nearest">
            <%= form.text_field :from_time, class: "form-control timepicker-input #{'is-invalid' if invalid}" %>
            <div class="input-group-append">
              <div class="input-group-text"><i class: "i class=" bi bi-stopwatch""></i></div>
            </div>
            <% if invalid %>
              <div class="invalid-feedback d-block">
                <% @leave_application.errors.full_messages_for(:from_time).each do |error_message| %>
                  <%= error_message %>.
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col">
        <% invalid = @leave_application.errors.include?(:to_time) %>
        <div class="from-group">
          <%= form.label :to_time %>
          <div class="input-group date" data-target-input="nearest">
            <%= form.text_field :to_time, class: "form-control timepicker-input #{'is-invalid' if invalid}" %>
            <div class="input-group-append">
              <div class="input-group-text"><i class: "i class=" bi bi-stopwatch""></i></div>
            </div>
            <% if invalid %>
              <div class="invalid-feedback d-block">
                <% @leave_application.errors.full_messages_for(:from_time).each do |error_message| %>
                  <%= error_message %>.
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div><br />
  <div class="field">
  <% invalid = @leave_application.errors.include?(:description) %>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "form-control #{'is-invalid' if invalid}" %>
    <% if invalid %>
      <div class="invalid-feedback d-block">
        <% @leave_application.errors.full_messages_for(:description).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div><br>
</div>

app/views/leave_applications/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg mx-auto">
      <div class="card my-5 shadow">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h3>Edit LeaveApplication</h3><br>
            </div>
            <div class="col-md-1 text-right">
              <%= link_to leave_applications_path, class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Back' do %>
                <i class='bi bi-arrow-left' aria-hidden='true'></i>
              <% end %>
            </div>
            <%= form_for @leave_application, :url => {:controller => 'leave_applications',:action => 'update'}, data: {turbo: false} do |form| %>
              <%= render 'form', :form => form %>
              <div class="col-md-12 text-end"><br />
                <%= form.submit "Update", class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Update' %>
              </div>
            <% end %>
          </div>
         </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/leave_applications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
      <div class="card my-5 shadow">
        <div class="card-body">
          <% if has_role_newuser? %>
            <div class="row mt-8">
              <div class="col-9">
                <h2>Listing All Leaves</h2><br>
              </div>
              <div class="col-3 text-end">
                <%= link_to new_leave_application_path, target: "_top", class: "btn btn-primary", data: {toggle: 'tooltip', placement: 'top'}, title: 'New Leave Application' do %>
                  <i class='bi bi-plus-circle-fill' aria-hidden='true'></i>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="col-md-12 text-end">
              <!-- %= button_to raw("<i class=\"bi bi-calendar2-week-fill\"></i>"), {:controller => :leave_applications, :action => :get_calculated_leaves}, {class: 'btn btn-success'} -----! % -->
            </div>
            <%= form_tag leave_applications_path, target: "_top", data: {toggle: 'tooltip', placement: 'top', title: 'Edit Update'},  method: :get do %>
              <div class="row mt-4">
                <div class="col-2"> 
                  <%= select_tag :user_id, options_for_select(@users_array, selected: params[:user_id]),{ include_blank: "All User", class: "form-control col-md-3 mr-1"} %>
                </div>
                <div class="col-2">
                  <%= select_tag :status, options_for_select(@status, selected: params[:status]),{ include_blank: "All Leave Type", class: "form-control col-md-3 mr-1" } %>
                </div>
                <div class="col-2">
                  <%= select_tag :order, options_for_select(@order, selected: params[:order]),{ include_blank: "By Order", class: "form-control col-md-3 mr-1" } %>
                </div>
                <div class ="col-2">
                  <div class="input-group date col-3" data-provide="date" >
                    <%= text_field_tag :from_date, params[:from_date], class: "form-control datepicker-input" %>
                    <div class="input-group-append">
                      <div class="input-group-text"><i class="bi bi-calendar3"></i></i></div>
                    </div>
                  </div>
                </div>
                <div class ="col-2">
                  <div class="input-group date col-3" data-provide="date" >
                    <%= text_field_tag :to_date, params[:to_date], class: "form-control datepicker-input" %>
                    <div class="input-group-append">
                      <div class="input-group-text"><i class="bi bi-calendar3"></i></i></div>
                    </div>
                  </div>
                </div><br>
                <div class="col-1">
                  <%= button_tag class: "btn btn-primary", data: {toggle: 'tooltip', placement: 'top'}, title: 'Find' do %>
                    <i class='bi bi-search' aria-hidden='true'></i>
                  <% end %>
                </div>
                <div class="reset">
                  <%= link_to leave_applications_path, class: 'btn btn-secondary', target: "_top", title: 'Clean' do %>
                    <i class='bi bi-x-lg' aria-hidden='true'></i>
                  <% end %>
                </div>
              </div></br>
            <% end %><br>
            <h2>Listing All Leaves</h2>
          <% end %>
          
          <table class="table">
            <thead class="thead-light">
              <tr>
                <% if has_role_admin? %>
                  <th>Name</th>
                <% end %>
                <th>Leave Type</th>
                <th class="col-6">Description</th>
                <th>From Date</th>
                <th>To Date</th>
                <th>Total Days</th>
                <th>Status</th>
                <% if has_role_admin? %>
                  <th>Apporved_By/ Rejected_By</th>
                <% end %>
                <th>
                  <% if @leave_applications.pluck(:status).include?("pending") %>
                    Actions
                  <% end %>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @leaves.each do |leave| %>
                <tr>
                  <% if has_role_admin? %>
                    <td><%= User.find(leave.user_id).name %></td>
                  <% end %>
                  <td><%= leave.leave_type %></td>
                  <td><%= leave.description %></td>
                  <% if leave.from_date.present? || leave.from_time.present?%>
                    <td>
                      <%= leave.half_day? ? leave.from_date.present? ? date_format(leave.from_date):date_format(Time.now) : date_format(leave.from_date) %>
                    </td>  
                  <% end %>
                  <% if leave.to_date.present?|| leave.to_time.present?%>
                    <td>
                      <%= leave.half_day? ? leave.to_date.present? ? date_format(leave.to_date):date_format(Time.now) : date_format(leave.to_date) %>
                    </td>
                  <% end %>
                  <% if leave.from_date && leave.to_date? || leave.from_time && leave.to_time?%>
                    <td><%= leave.half_day? ? 'Half Day' : leave.total_day %></td>
                  <% end %>
                  <td><%= leave.status %></td>
                  <% if leave.apporved_by.present? && has_role_admin? %>
                    <td><%= leave.apporved_by %></td>
                  <% end %>
                  <td>
                    <% if leave.pending? && has_role_admin? %>
                    <td class="col-1">
                      <%= link_to approve_leave_application_path(leave.id), class: "btn btn-success btn-sm", data: {toggle: 'tooltip', placement: 'top'}, title: 'Approve Leave' do %>
                        <i class='bi bi-check-lg' aria-hidden='true'></i>
                      <% end %>
                      <%= link_to reject_leave_application_path(leave.id), class: "btn btn-danger btn-sm", data: {toggle: 'tooltip', placement: 'top'}, title: 'Reject Leave' do %>
                        <i class='bi bi-x' aria-hidden='true'></i>
                      <% end %>
                    </td>
                    <% elsif leave.pending? && has_role_newuser? %>
                      <%= link_to  edit_leave_application_path(leave), target: "_top", class: "btn btn-success btn-sm", data: {toggle: 'tooltip', placement: 'top'}, title: 'Edit Leave' do %>
                        <i class='bi bi-pencil-fill' aria-hidden='true'></i>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="pagination justify-content-center">
            <%= paginate @leaves, theme: 'bootstrap-5', pagination_class: "pagination-sm", nav_class: "d-inline-b" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/leave_applications/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg mx-auto">
      <div class="card my-5 shadow">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h3>New LeaveApplication</h3><br>
            </div>
            <div class="col-md-1 text-end">
              <%= link_to leave_applications_path, class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Back' do %>
                <i class='bi bi-arrow-left' aria-hidden='true'></i>
              <% end %>
            </div>
            <%= form_for @leave_application, url: leave_applications_path, data: {turbo: false}, method: :post do |form| %>
              <%= render 'form', :form => form %></br >
              <div class="col-md-12 text-end">
                <%= form.submit "Save", class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Save' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>