config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  get 'organizations/index'
  get 'organizations/admin_index'
  get 'organizations/:id/super_fetaure_edit', to: 'organizations#super_fetaure_edit', as: :super_fetaure_edit
  patch 'organizations/:id', to: 'organizations#super_fetaure_update', as: :super_fetaure_update
  get 'properties/index'
  get 'users/index'
  get 'periods/index'
  get 'periods/new'
  get 'passwords/edit', to: 'passwords#edit'
  post 'updates/new'
  post 'leave_applications/new'
  post 'leave_applications/get_calculated_leaves'
  get  'employees',  to: 'users#new'
  post 'employees',  to: 'users#add_user'
  get 'leave_balances/index'
  get 'users/switch_and_redirect_view'
  resources :passwords do
    member do
      get 'edit_password'
      patch 'edit_password'
      patch 'update_password'
    end
  end
  resources :leave_days 
  resources :notifications 
  resources :organizations
  resources :properties
  resources :bonds

  resources :groups do 
    resources :messages
  end

  resources :users do
    member do
      get 'user_profile'
      get 'edit_user'
      patch 'edit_user'
      patch 'update_user'
      post 'assign_admin_role'
      post 'remove_admin_role'
      resources :projects
    end
  end
  
  resources :updates do 
    collection { post :import}
  end
  
  resources :leave_applications do
    member do
      patch 'approve'
      get 'approve'
      patch 'reject'
      get 'reject'
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :projects
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  acts_as_paranoid

  has_many :users, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :properties, dependent: :destroy
  has_many :leave_applications, dependent: :destroy
  has_many :leave_days, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :leave_balances, dependent: :destroy
  has_one :feature_flag, dependent: :destroy
  has_many :bonds, dependent: :destroy

  accepts_nested_attributes_for :feature_flag
  
  validates :name, presence: true, uniqueness: true

  def specified_role_users(role)
    users.with_role(role)
  end

  def self.calculated_lefted_leaves_of_the_month(organization)
    organization.users.each do |user|
      count = LeaveBalance.where("user_id = ? AND organization_id = ? AND (DATE(leave_date) BETWEEN ? AND ?)", user.id, organization.id, Date.today.beginning_of_month, Date.today.end_of_month).count
      u = User.find(user.id)
      total = count - 1.5 + u.lefted_leave
      if total < 0 
        u.update(lefted_leave: total) 
      else
        u.update(lefted_leave: 0.0)
      end
    end
  end

  FEATURE_FLAGS.each do |flag|
    define_method("#{flag}_on?") do
      if self.respond_to?("#{flag}_on?")
        fg = feature_flag
        if fg.send(flag) == 'on'
          true
        else 
          false
        end
      end
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.page(params[:page]).per(5)
  end

  def admin_index
    @organizations = current_user.organization
  end

  def super_fetaure_edit
    @organization = Organization.find(params[:id])
    @feature_flag = FeatureFlag.find_or_create_by(organization_id: @organization.id)
  end

  def super_fetaure_update
    @organization = Organization.find(params[:id])
    if @organization.update!(organization_params)
      redirect_to organizations_index_path, notice: 'Organization was successfully updated'
    else
      render :super_fetaure_edit
    end
  end
  
  def show
    @organization = Organization.find(params[:id])
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    respond_to do |format|
      if @organization.save
        format.html { redirect_to organizations_index_path,  notice: 'Organization was successfully created.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('organization_form',
          partial: 'organizations/form',
          locals: { organization: @organization })
        end
      end
    end
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organizations_index_path,  notice: 'Organization was successfully updated.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('organization_form',
          partial: 'organizations/form',
          locals: { organization: @organization })
        end
      end
    end
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    redirect_to organizations_index_path, notice: 'Organization was successfully destroyed.'
  end

  private

  def organization_params
    params.require(:organization).permit(:name, weekly_off: [], feature_flag_attributes: [:id, :employee_bond, :organization_id] )
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<div id="organization_form">
  <%= form_with(model: organization, id: "#{dom_id(organization)}_form") do |form| %>
    <div class="container">
      <div class="row mt-3">
        <div class="row">
          <div class="col">
            <% invalid = organization.errors.include?(:name) %>
            <div class="form-group col-8">
              <%= form.text_field :name, class: "form-control #{'is-invalid' if invalid}",placeholder: "name", :readonly => (current_user.has_role_admin ? true : false) %>
              <% if invalid %>
                <div class="invalid-feedback d-block">
                  <% organization.errors.full_messages_for(:name).each do |error_message| %>
                    <%= error_message %>.
                  <% end %>
                </div>
              <% end %>
            </div><br>
          </div>
        </div>
        <% if current_user.has_role_admin %>
         <div class="row">
          <div class="col-5  btn-group dropup">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              Select weekly off days
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <% weekly_off = ["Sunday", "Monday", "Tuesday","wednesday","Thursday","Friday","Saturday"] %>
              <% weekly_off.each do |weekly_off| %>
                <%= form.check_box :weekly_off, { multiple: true }, weekly_off, nil %> 
                <%= weekly_off %><br>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="col-6">
          <%= form.submit class: "btn btn-primary" %>
        </div>
      </div>
      </div>
    </div>
  <% end %>
</div>

app/views/organizations/_organization.html.erb
<li class="py-2 px-4 border-b border-gray-300">
  <%= organization.name %>
</li>

app/views/organizations/admin_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
      <div class="card my-5 shadow">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h2>Organizations</h2><br>
            </div>
              <div class="col-md-7 text-end">
                <%= link_to organizations_admin_index_path, target: "_top" ,class: "btn btn-secondary", title: 'Clean'  do%> 
                  <i class='bi bi-x-lg' aria-hidden='true'></i>                  
                <% end %>
              </div>
              <table class="table table-hover">
                <thead class="thead-light">
                  <th>Name</th>
                  <th>Admin List</th>
                  <th>Action</th>
                </thead>
                <div class="col-sm-4">
                  <tr>
                    <td>
                      <id="<%= "#{dom_id(@organizations)}_container" %>" class="py-2 px-4 border-b border-gray-300">
                      <%= turbo_frame_tag dom_id(@organizations) do %>
                        <%= link_to @organizations.name, edit_organization_path(@organizations.id), class: 'btn btn-link', disabled: :disabled %>
                      <% end %>
                    </td>
                    <td class="col-3-admin-list">
                      <%= @organizations.specified_role_users(:admin).pluck(:email).join(', ') %>
                    </td>
                    <div class="actions">
                      <td>
                        <%= link_to new_user_path(organization_id: @organizations.id), target: "_top", class: "btn btn-primary btn-sm", data: {toggle: 'tooltip', placement: 'top'}, title: 'Create Admin' do %>
                          <i class='bi bi-plus-circle-fill' aria-hidden='true'></i>
                        <% end %>
                      </td>
                    </div>
                  </tr>
                </div>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/create.turbo_stream.erb
<%= turbo_stream.prepend "organizations" do %>
  <%= render "organization", organization: @organization %>
<% end %>
<%= turbo_stream.replace "#{dom_id(Organization.new)}_form" do %>
  <%= render "form", organization: Organization.new %>
<% end %>

app/views/organizations/edit.html.erb
<%= turbo_frame_tag dom_id(@organization) do %>
  <%= render "form", organization: @organization %>
<% end %>

app/views/organizations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card my-5 shadow">
        <div class="card-body">
          <div class="col-md-12 text-right">
            <h2>Organizations</h2>
            <div class="w-full max-w-2xl bg-gray-100 py-8 px-4 border border-gray-200 rounded shadow-sm">
              <div class="py-2 px-4">
                <%= link_to organizations_index_path, target: "_top" ,class: "btn btn-secondary float-end"  do %> 
                  <i class='bi bi-x-lg' aria-hidden='true'></i>                  
                <% end %><br />
                <%= render "form", organization: @organizations.new %>
              </div>
            </div>
            <table class="table table-hover">
              <thead class="thead-light">
                <th>Name</th>
                <th>Admin List</th>
                <th>Action</th>
              </thead>
              <div class="col-sm-4">
                <% @organizations.each do |organization| %>
                  <tr>
                    <td>
                      <%= organization.name %>
                    </td>
                    <td>
                      <%= organization.specified_role_users(:admin).pluck(:email).join(', ') %>
                    </td>
                    <td class="col-2">
                      <%= link_to organization_path(organization.id), method: :delete , data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-sm btn-danger", toggle: 'tooltip', placement: 'top', title: 'Destroy Organization' do %>
                        <i class='bi bi-trash3-fill' aria-hidden='true'></i>
                      <% end %>
                      <%= link_to super_fetaure_edit_path(organization.id), target: "_top", class: "btn btn-success btn-sm", data: {toggle: 'tooltip', placement: 'top', title: 'Create Admin'} do %>
                        <i class='bi bi-pencil-fill' aria-hidden='true'></i>
                      <% end %>
                      <% if !organization.users.with_role(:superadmin).present? %>
                        <%= link_to new_user_path(organization_id: organization.id), target: "_top", class: "btn btn-primary btn-sm", data: {toggle: 'tooltip', placement: 'top', title: 'Create Admin'} do %>
                          <i class='bi bi-plus-circle-fill' aria-hidden='true'></i>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </div>
            </table>
            <div class="pagination justify-content-center">
              <%= paginate @organizations, theme: 'bootstrap-5', pagination_class: "pagination-sm", nav_class: "d-inline-b" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/new.html.erb
<h1>New Organization</h1>
<%= render "form", organization: @organization %>

app/views/organizations/show.html.erb
<%= @organization.name%><br>
<%= link_to 'Back', organizations_path %>

app/views/organizations/super_fetaure_edit.html.erb
<%= form_for @organization, url: { controller: "organizations", action: "super_fetaure_update" }, method: :patch do |f| %>
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="card my-5 shadow">
          <div class="card-body">
          <div class="col-md-12 text-end">
            <%= link_to organizations_index_path, class: "btn btn-primary", data: {toggle: 'tooltip', placement: 'top', title: 'Edit Update'} do %>
              <i class='bi bi-arrow-left' aria-hidden='true'></i>
            <% end %>
          </div>
          <h1>Edit Organization</h1>
            <div class="row mt-3">
              <div class="col">
                <% invalid = @organization.errors.include?(:name) %>
                <div class="form-group">
                  <%= f.label :organization_name %>
                  <%= f.text_field :name, class: "form-control #{'is-invalid' if invalid}",placeholder: "name", :readonly => (current_user.has_role_admin ? true : false) %>
                  <% if invalid %>
                    <div class="invalid-feedback d-block">
                      <% organization.errors.full_messages_for(:name).each do |error_message| %>
                        <%= error_message %>.
                      <% end %>
                    </div>
                  <% end %>
                </div><br/>
              </div>
              <div class="col">
                <% if current_user.has_role? :superadmin %>
                  <%= f.fields_for :feature_flag do |attr_flag| %>
                    <% FEATURE_FLAGS.each do |feature| %>
                      <%= hidden_field_tag "organization[feature_flag_attributes][id]", @feature_flag.id %>
                      <%= hidden_field_tag "organization[feature_flag_attributes][organization_id]", @feature_flag.organization_id %>
                      <%= feature.to_s.titlecase %>
                      <% object = attr_flag.object %>
                      <%= attr_flag.select feature.to_sym, ["off", "on"], {selected: object.send(feature) }, class: "form-control" %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div><br />
            <div class="col float-end">
              <%= f.submit "Update organization",class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>